---
#
# Ansible managed
#
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
lint: |
  set -e
  yamllint .
  ansible-lint
driver:
  name: docker
platforms:
  - name: "testconnection-${image:-docker-centos7-ansible}-${tag:-latest}${TOX_ENVNAME}"
    image: "${namespace:-buluma}/${image:-docker-centos7-ansible}:${tag:-latest}"
    command: /sbin/init
    exposed_ports:
      - 22/tcp
    published_ports:
      - 0.0.0.0:22:22/tcp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: yes
    pre_build_image: yes
    tty: true
    environment:
      container: docker
  - name: "testconnection-${image:-docker-centos8-ansible}-${tag:-latest}${TOX_ENVNAME}"
    image: "${namespace:-buluma}/${image:-docker-centos8-ansible}:${tag:-latest}"
    command: /sbin/init
    exposed_ports:
      - 22/tcp
    published_ports:
      - 0.0.0.0:23:22/tcp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: yes
    pre_build_image: yes
    tty: true
    environment:
      container: docker
  - name: "testconnection-${image:-fedora}-${tag:-latest}${TOX_ENVNAME}"
    image: "${namespace:-buluma}/${image:-fedora}:${tag:-latest}"
    command: /sbin/init
    exposed_ports:
      - 22/tcp
    published_ports:
      - 0.0.0.0:24:22/tcp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: yes
    pre_build_image: yes
    tty: true
    environment:
      container: docker
  - name: "testconnection-${image:-fedora-systemd}-${tag:-latest}${TOX_ENVNAME}"
    image: "${namespace:-buluma}/${image:-fedora-systemd}:${tag:-latest}"
    command: /sbin/init
    exposed_ports:
      - 22/tcp
    published_ports:
      - 0.0.0.0:25:22/tcp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: yes
    pre_build_image: yes
    tty: true
    environment:
      container: docker
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_legacy_silent
verifier:
  name: ansible
