---
# image: "ghcr.io/mullholland/docker-molecule-shell:latest"
image: "buluma/github-action-molecule:5.0.0"

# services:
# - docker:dind

stages:
  - linting
  - "default-previous"
  - "default-current"

variables:
  # DOCKER_HOST: "tcp://docker:2375"
  PY_COLORS: 1
  ANSIBLE_FORCE_COLOR: 1

linting:
  tags:
    - ec2-af-south-1
  stage: linting
  variables:
    COMMAND: "lint"
  script:
    # - "command=${COMMAND} /opt/molecule.sh"
    - "ansible-lint ."
    - "yamllint ."


"default-previous":
  tags:
    - ec2-af-south-1
  needs:
    - "linting"
  stage: "default-previous"
  variables:
    SCENARIO: "default"
    ANSIBLE: "previous"
  rules:
    - if: $CI_COMMIT_REF_NAME == "testing"
  parallel:
    matrix:
      - PLATFORM: [debian9, debian10, debian11, ubuntu1804, ubuntu2004, ubuntu2204, centos7, centos-stream8, centos-stream9, ubi8, fedora35, fedora36, amazonlinux]  # yamllint disable-line rule:line-length
  script:
    # - "scenario=${SCENARIO} ansible=${ANSIBLE} platform=${PLATFORM} /opt/molecule.sh"
    - "molecule test"

"default-current":
  tags:
    - ec2-af-south-1
  allow_failure: true
  needs:
    - "linting"
  stage: "default-current"
  variables:
    SCENARIO: "default"
    ANSIBLE: "current"
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
  parallel:
    matrix:
      - PLATFORM: [debian9, debian10, debian11, ubuntu1804, ubuntu2004, ubuntu2204, centos7, centos-stream8, centos-stream9, ubi8, fedora35, fedora36, amazonlinux]  # yamllint disable-line rule:line-length
  script:
    - molecule test
