---
#
# Ansible managed
#
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
lint: |
  set -e
  yamllint .
  ansible-lint
driver:
  name: docker
platforms:
  - name: "testconnection-${image:-docker-centos7-ansible}-${tag:-latest}${TOX_ENVNAME}"
    image: "${namespace:-buluma}/${image:-docker-molecule-images}:${tag:-latest}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: yes
    pre_build_image: yes
    tty: true
    environment:
      container: docker
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_legacy_silent
verifier:
  name: ansible
